---

- hosts: all
  gather_facts: true


  tasks:
#    - name: remove old directory {{ inventory_hostname }}
#      shell: 'rm -rf /tmp/files'

    - name: copy the files from repo {{ inventory_hostname }}
      copy:
        src: files
        dest: /tmp/

    - name: Check the isAlive details {{ inventory_hostname }}
      shell: 'chmod -R 777 /tmp/files'


    - name: Check the files from repo {{ inventory_hostname }}
      shell: 'ls -ltr;pwd'
      register: filelist

    - debug:
        msg: "{{ filelist.stdout_lines }}"

    - name: Check the isAlive details {{ inventory_hostname }}
      shell: 'cd /tmp/files;/usr/bin/python main.py -f urlslist.txt'
      register: isAlive

    - debug:
        msg: "{{ isAlive.stdout_lines }}"

    - name: sending email
      shell: 'cd /tmp/files;/usr/bin/sh sendemail.sh'
      register: email_out

    - debug:
        msg: "{{ email_out.stdout_lines }}"

#    - name: Check the isAlive details {{ inventory_hostname }}
#      shell: 'chmod -R 777 /tmp/files'
